@Library('freelance') _
import com.example.*

pipeline {
   agent any
   stages {
        stage('library groovy') {
			steps {
				script {
					Pipeline hamada = new Pipeline("config.yaml")
					hamada.execute()
				}
			}
		}				
	}
}
