@Library('freelance') _
import com.example.*

pipeline {
   agent any
   stages {
        stage('library groovy') {
			steps {
				script {
					Pipeline hamada = new Pipeline(this, "config.yaml")
					println(hamada.configurationFile)
					hamada.execute()				
				}
			}
		}				
	}
}
